[project]

name = "EmmaAssistent"
version = "0.1.0"
description = "Аналізатор почти"
readme = "README.md"
requires-python = ">=3.9"
authors = [
  { name = "Andrii Borch", email = "skabinausa@gmail.com" }
]
dependencies = [

]